#!/bin/sh
# 50-fault-injection.sh - RANDOM_ERROR_RATE for the frontend, the same knob the backend has.
#
# The progressive-delivery lab (Chapter 19) needs a frontend release that fails for some of its
# users: a canary whose error rate the analysis catches. The frontend is static files and a proxy,
# so nothing in it fails on its own; this makes nginx answer 500 to a share of requests instead.
#
# RANDOM_ERROR_RATE is a probability, 0 to 1 (like the backend's): 0.3 means about three requests
# in ten get a 500. Unset or 0 - nothing fails. /health is never failed: the probes must keep
# seeing a healthy pod, so the errors reach users and the analysis, not the kubelet (pods that go
# NotReady would leave the Service instead of failing requests).
#
# Run by the nginx image's /docker-entrypoint.sh before nginx starts, on every container start.
# Writes /tmp/nginx-fault.conf (the root filesystem is read-only in the cluster; /tmp is an
# emptyDir), which nginx.conf includes in its http block. Exits non-zero on an invalid value, and the
# entrypoint then stops the container: a typo must not silently mean "no errors".
set -eu

rate="${RANDOM_ERROR_RATE:-0}"

# 0, 1, or a decimal between them: 0.3, .25, 1.0. Anything else is refused.
if ! printf '%s' "${rate}" | grep -Eq '^(0|1|0?\.[0-9]+|1\.0+|0\.0*)$'; then
  echo "50-fault-injection.sh: RANDOM_ERROR_RATE='${rate}' is not a probability between 0 and 1" >&2
  exit 1
fi

# split_clients takes a percentage: 0.3 -> 30.00%. With 0 every request lands in "*" -> 0.
percent="$(awk -v r="${rate}" 'BEGIN { printf "%.2f", r * 100 }')"

{
  echo "# Generated by /docker-entrypoint.d/50-fault-injection.sh from RANDOM_ERROR_RATE=${rate}"
  echo "split_clients \"\${request_id}\" \$fault_roll {"
  if [ "${percent}" != "0.00" ]; then
    echo "    ${percent}% 1;"
  fi
  echo "    * 0;"
  echo "}"
  echo "# /health is exempt: the probes must see a healthy pod (see the script)."
  echo "map \"\$fault_roll:\$uri\" \$fault_inject {"
  echo "    default 0;"
  echo "    \"~^1:/health\$\" 0;"
  echo "    \"~^1:\" 1;"
  echo "}"
} > /tmp/nginx-fault.conf

if [ "${percent}" != "0.00" ]; then
  echo "50-fault-injection.sh: RANDOM_ERROR_RATE=${rate} - about ${percent}% of requests answer 500 (/health excepted)"
fi
